language: php

php:
  - 7.1
  - 7.2
  - 7.3

install:
  - composer update
  - wget https://github.com/swoole/swoole-src/archive/v4.3.5.tar.gz -O swoole.tar.gz && mkdir -p swoole && tar -xf swoole.tar.gz -C swoole --strip-components=1 && rm swoole.tar.gz && cd swoole && phpize && ./configure && make -j$(nproc) && make install && cd -
  - echo "extension = swoole.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_script:
  - composer config -g process-timeout 9000 && composer update
  - phpenv config-rm xdebug.ini

script:
  - composer test
