sudo: required
language: php
dist: trusty

matrix:
  include:
  - php: '5.5'
    env: PHPUNIT_VERSION="4"
  - php: '5.6'
    env: PHPUNIT_VERSION="5"
  - php: '7.0'
    env: SWOOLE_VERSION="v4.3.6"
  - php: '7.1'
    env: SWOOLE_VERSION="v4.3.6"
  - php: '7.2'
    env: SWOOLE_VERSION="v4.3.6"
  - php: '7.3'
    env: SWOOLE_VERSION="v4.3.6"
  - php: '7.1'
    env: SWOOLE_VERSION="v4.4.14"
  - php: '7.2'
    env: SWOOLE_VERSION="v4.4.14"
  - php: '7.3'
    env: SWOOLE_VERSION="v4.4.14"
  - php: '7.4'
    env: SWOOLE_VERSION="v4.4.14"
  - php: '7.1'
    env: SWOOLE_VERSION="master"
  - php: '7.2'
    env: SWOOLE_VERSION="master"
  - php: '7.3'
    env: SWOOLE_VERSION="master"
  - php: '7.4'
    env: SWOOLE_VERSION="master"
  - php: 'nightly'
    env: SWOOLE_VERSION="master" DISABLE_XDEBUG=false PHPUNIT_VERSION="7" INSTALL_REDIS_EXT=true
  allow_failures:
  - env: SWOOLE_VERSION="master"
  - php: nightly

env:
  global:
    - HTTP_SERVER_HOST=http://127.0.0.1:8898/
    - WS_SERVER_HOST=ws://127.0.0.1:8900/

services:
  - redis-server

addons:
  apt:
    packages:
    - nginx

install:
  - if [[ $INSTALL_REDIS_EXT == true ]]; then
      wget https://github.com/phpredis/phpredis/archive/develop.zip;
      unzip develop.zip;
      cd phpredis-develop;
      phpize;
      ./configure;
      make && make install;
      cd ../;
    fi
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "always_populate_raw_post_data=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - if [[ $SWOOLE_VERSION ]]; then
      wget https://github.com/swoole/swoole-src/archive/$SWOOLE_VERSION.tar.gz -O swoole.tar.gz && mkdir -p swoole && tar -xf swoole.tar.gz -C swoole --strip-components=1 && rm swoole.tar.gz && cd swoole && phpize && ./configure --enable-openssl --enable-http2 && make -j && make install && cd -;
      echo "extension = swoole.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini;
      php --ri swoole;
      wget https://github.com/Yurunsoft/swoole-binary/releases/download/v4.4.12/swoole_4.4.12_e48bc457_x86-64_linux.tar.xz;
      mkdir -p /opt/swoole;
      tar -C /opt/swoole -xvf swoole_4.4.12_e48bc457_x86-64_linux.tar.xz;
      /opt/swoole/bin/php --ri swoole;
    fi

before_script:
  - if [[ $DISABLE_XDEBUG != false ]]; then
      phpenv config-rm xdebug.ini;
    fi
  - if [[ $PHPUNIT_VERSION ]]; then
      curl -sSfL -o ~/.phpenv/versions/$(phpenv version-name)/bin/phpunit https://phar.phpunit.de/phpunit-$PHPUNIT_VERSION.phar;
    fi
  - sudo cp $TRAVIS_BUILD_DIR/.travis/default.vhost /etc/nginx/sites-available/default.vhost
  - sudo ln -s /etc/nginx/sites-available/default.vhost /etc/nginx/sites-enabled/default.vhost
  - sudo service nginx reload
  - date
  - env
  - uname -a
  - ulimit -a
  - ls -al
  - pwd
  - php -v
  - php -m
  - php --ri redis
  - php --ri curl;
  - php --ri openssl;

script:
  - composer install-test-no-dev
